[build]
  functions = "built-functions"

[[redirects]]
  from = "/cloudinary"
  to = "https://new-models.netlify.com/.netlify/functions/cloudinary"

[[redirects]]
  from = "/metadata/*"
  to = "https://new-models.netlify.com/.netlify/functions/metadata/:splat"